### ISSUE TITLE
Encontrei um bug no Zupdator.exe

### ISSUE THREAD

**Issue by TheDanielz3** [serialtasted/arma3Launcher#14]
Boas Serial!,

Eu quando dei update no Zupdate quando jogo pediu eu executei... ele começou a dar alguns problemas de conseguir encontrar o launcher e assim.
Pelo qual eu quero explicar o sucedido.
Digamos que quando o jogo Update o Zupdate disse que nao podia ter mais que um executável do launcher o que eu dei close e reiniciei a maquina (dei logout) para dar fix. Ai eu voltei a abrir deu o mesmo erro eu em fez de dar ok eu fechei na cruz e consegui dar update nao sei como... 

Alguma coisa fala comigo

Danielz

**Comment by serialtasted** [comment]
Fiquei muito confuso com esta descrição. Quando dizes jogo queres dizer launcher?

**Comment by TheDanielz3** [comment]
> Fiquei muito confuso com esta descrição. Quando dizes jogo queres dizer launcher?

Sim o Launcher.. A3launcher

**Comment by serialtasted** [comment]
Fixed on new version of zUpdator
