### ISSUE TITLE
Nuget Packges

### ISSUE THREAD

**Issue by BLueTyPEXYZ** [serialtasted/arma3Launcher#18]
My Nuget Packges are Broke. Pls Fix

**Comment by serialtasted** [comment]
Please include more info

**Comment by BLueTyPEXYZ** [comment]
Visual Studio Codes says every time i dont have the nuget packges but i had install them. the dicetory is correctly

**Comment by serialtasted** [comment]
Probably same as this: https://github.com/serialtasted/arma3Launcher/issues/19
