### ISSUE TITLE
Add pause to the download queue

### ISSUE THREAD

**Issue by Tiagone** [serialtasted/arma3Launcher#2]
Just to ask if an pause / resume button can be had to the Launcher. And maybe a "Just uptade" button.

Continue the great work. 

Thanks

**Comment by serialtasted** [comment]
Closing the launcher will stop all downloads and save what was already downloaded. When opening the launcher again it'll ask to resume. As of version 1.3 it's possible to find a preferences menu in the "More Options" tab (top right, next to close and minimize buttons), whit a "don't run the game" option.
