### ISSUE TITLE
The A3L Repo file.

### ISSUE THREAD

**Issue by ScaredDonut** [serialtasted/arma3Launcher#20]
Hi there,

I got a bit of the noob question, how exactly do you generate an A3L file? I was gonna do one myself but I am not sure what the first set of numbers is.
Ex: (314368*20190503234827*@ace\ace_advanced_ballistics_x64.dll)
 I assumed it was the ArmA 3 Launcher tool, so I downloaded it, but I didn't see a way to generate a a3l anywhere on it.

Sorry for the noob question and thanks for your time and help!

**Comment by serialtasted** [comment]
Oh damn. I'm so sorry I didn't see this here. Are you still interested in this issue?

**Comment by ScaredDonut** [comment]
Not a problem and yes please!  Thanks! :)

**Comment by serialtasted** [comment]
In the repository list right click on the darker area and press manage repository. There you can select the folder where your add-ons are. A file will be created in that directory with all that information.

Folder structure

root add-ons folder
 |- @"addonname"
    |- addonfiles
 |- @"addonname"
    |- addonfiles
 |- repofile

If you want the launcher to use your custom file you need to change the address to the file that is in the settings of the program. This is hardcoded.

If you want any more help add me on steam: serialtasted

**Comment by ScaredDonut** [comment]
Awesome, thanks! :)
