### ISSUE TITLE
The project data are incorrect

### ISSUE THREAD

**Issue by pat2381** [serialtasted/arma3Launcher#21]
Hello Serialtasted, 
it's fantastic what you've created here. I would like to continue your project in a different way, unfortunately the VS project can only be opened with a lot of errors. Is it possible that you can upload it again cleanly with a VS project file. That would be great.

Best regards, Mr.Jim

**Comment by serialtasted** [comment]
Hey there,
Can you send me the log? Cause I usually use this to restore the project when I format my computer and it goes smoothly

**Comment by pat2381** [comment]
Hello, I've been working all the time to get it to work. I saw that you are using a different MaterialSkin than the one in NuGet. It looks pretty good now. The only thing that doesn't fit right now is the custom controls, I think there are several files missing xxx.designer.cs. When I try to open the MainForm I get an error that the DoubleBufferPanel cannot be found. But when I create the project, the exe works. What's wrong here? Can you help me please?

The other question is how do you create a config.xml? Is there another program or is there one that can be created?

![Arma3Launcher](https://user-images.githubusercontent.com/22663681/101224178-3fe28d80-368e-11eb-839e-25b2e927d04f.JPG)
![Arma3Launcher2](https://user-images.githubusercontent.com/22663681/101224179-407b2400-368e-11eb-9f7f-9b93fa363c68.JPG)

**Comment by serialtasted** [comment]
- Check https://github.com/serialtasted/arma3Launcher/releases/latest for the zip file with the full project inside
- Check ftp://ptrserver.ddns.net/arma3Launcher/ for the XML, images and folder structure references

The XML file was done manually. I had the idea to do it using the launcher but never done that component
