### ISSUE TITLE
Data file too short

### ISSUE THREAD

**Issue by ramant3** [serialtasted/arma3Launcher#6]
I just downloaded all mods available to download and when i tried to launch through the launcher it just gave this error

<a href="http://tinypic.com?ref=14uvqld" target="_blank"><img src="http://i59.tinypic.com/14uvqld.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by serialtasted** [comment]
Does the problem persist?

**Comment by ramant3** [comment]
all the time i launch the application

**Comment by serialtasted** [comment]
Delete addon folder "@ASDG" and download it again. Should fix it
