### ISSUE TITLE
Cancel download button

### ISSUE THREAD

**Issue by josemotanet** [serialtasted/arma3Launcher#8]
When trying the app, I realized it would be important to allow the user to cancel a download, regardless of reason.

If I have the time, I'd like to submit a PR to add the feature. I'm stuck on a 2GB+ mod downloading and I can't stop it. :disappointed: 

On a note: may be related to #2 ?

**Comment by serialtasted** [comment]
Right now, if you close the launcher it will cancel the current download and save what has been already downloaded to your system.

**Comment by josemotanet** [comment]
Oh, ok. Thanks for pointing it out! :+1:

Closing.
