### ISSUE TITLE
Issue while opening Arma 3 trough PTRangers Launcher

### ISSUE THREAD

**Issue by Tiagone** [serialtasted/arma3Launcher#9]
While trying to open the game trough the launhcer i get this error
![erro arma 3](https://cloud.githubusercontent.com/assets/13615395/12246432/5ac54702-b8a6-11e5-8925-947bac851648.jpg)

**Comment by serialtasted** [comment]
Not a launcher problem

**Comment by serialtasted** [comment]
https://forums.bistudio.com/topic/182076-the-application-was-unable-to-start-correctly-0xc000009a-battleeye-update-issue/
